language: node_js

branches:
  only:
    - master

cache: yarn

install:
  - yarn

jobs:
  include:
    - stage: lint
      node_js: '8'
      script:
        - npm run lint
    - stage: test
      node_js: '8'
      script:
        - npm run test-unit
        - npm run test-e2e

stages:
  - lint
  - test